# Generated by Django 6.0.6 on 2026-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tuition_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='مبلغ شهریه (تومان)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuition_due_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ سررسید شهریه'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuition_status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=10, verbose_name='وضعیت شهریه'),
        ),
    ]
