# Generated by Django 6.0.6 on 2026-08-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_tuition_amount_user_tuition_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tuition_due_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tuition_status',
        ),
        migrations.AddField(
            model_name='user',
            name='last_payment_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='آخرین پرداخت (مثلاً 1405/05/10)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuition_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='روز پرداخت شهریه (۱ تا ۳۰)'),
        ),
    ]
