# Generated by Django 6.0.6 on 2026-07-06 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='روز و تاریخ')),
                ('course_name', models.CharField(max_length=100, verbose_name='نام درس')),
                ('study_time', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='زمان مطالعه (ساعت)')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='تعداد تست درست')),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name='تعداد تست غلط')),
                ('unanswered', models.PositiveIntegerField(default=0, verbose_name='تعداد تست نزده')),
                ('test_time', models.PositiveIntegerField(default=0, verbose_name='زمان تست (دقیقه)')),
                ('topic', models.CharField(max_length=200, verbose_name='مبحث مورد مطالعه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'گزارش کار',
                'verbose_name_plural': 'گزارش\u200cهای کار',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='تاریخ برنامه')),
                ('course_name', models.CharField(max_length=100, verbose_name='نام درس')),
                ('study_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان مطالعه (اختیاری)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده'), ('missed', 'انجام نشده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_plans', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'برنامه درسی',
                'verbose_name_plural': 'برنامه\u200cهای درسی',
                'ordering': ['-plan_date', '-created_at'],
            },
        ),
    ]
