# Generated by Django 6.0.6 on 2026-07-06 12:02

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=django_jalali.db.models.jDateField(verbose_name='روز و تاریخ'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='plan_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ برنامه'),
        ),
    ]
