# Generated by Django 6.0.6 on 2026-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_alter_report_report_date_alter_studyplan_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.CharField(max_length=20, verbose_name='روز و تاریخ'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='plan_date',
            field=models.CharField(max_length=20, verbose_name='تاریخ برنامه'),
        ),
    ]
