# Generated by Django 6.0.6 on 2026-08-08 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_alter_report_report_date_alter_studyplan_plan_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هدف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('target_type', models.CharField(choices=[('study_hours', 'ساعت مطالعه'), ('tests', 'تعداد تست'), ('lessons', 'تعداد درس')], default='study_hours', max_length=20, verbose_name='نوع هدف')),
                ('target_value', models.PositiveIntegerField(default=20, verbose_name='مقدار هدف (ساعت/تعداد)')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='پیشرفت فعلی')),
                ('start_date', models.CharField(max_length=20, verbose_name='تاریخ شروع')),
                ('end_date', models.CharField(max_length=20, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'هدف',
                'verbose_name_plural': 'اهداف',
                'ordering': ['-created_at'],
            },
        ),
    ]
