# Generated by Django 6.0.6 on 2026-08-08 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0004_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='جمله انگیزشی')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='نویسنده')),
                ('day_of_year', models.PositiveIntegerField(unique=True, verbose_name='روز سال (۱ تا ۳۶۵)')),
            ],
            options={
                'verbose_name': 'جمله انگیزشی',
                'verbose_name_plural': 'جملات انگیزشی',
                'ordering': ['day_of_year'],
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هدف')),
                ('goal_type', models.CharField(choices=[('study_hours', '📚 ساعت مطالعه'), ('tests', '📝 تعداد تست'), ('lessons', '📖 تعداد درس'), ('exercise', '🏃 ورزش'), ('meditation', '🧘 مدیتیشن'), ('reading', '📕 کتاب\u200cخوانی'), ('custom', '✨ شخصی\u200cسازی')], default='study_hours', max_length=20, verbose_name='نوع هدف')),
                ('target_value', models.PositiveIntegerField(default=20, verbose_name='مقدار هدف')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='پیشرفت فعلی')),
                ('start_date', models.CharField(max_length=20, verbose_name='تاریخ شروع')),
                ('end_date', models.CharField(max_length=20, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'هدف',
                'verbose_name_plural': 'اهداف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تسک')),
                ('date', models.CharField(max_length=20, verbose_name='تاریخ')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'تسک شخصی',
                'verbose_name_plural': 'تسک\u200cهای شخصی',
                'ordering': ['date', '-created_at'],
            },
        ),
    ]
