# Generated by Django 6.0.6 on 2026-08-12 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_color_course_icon'),
        ('counseling', '0005_motivationalquote_studentgoal_studenttodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='core.course', verbose_name='درس (انتخاب از لیست)'),
        ),
    ]
