# Generated by Django 6.0.6 on 2026-08-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_color_remove_course_icon'),
        ('counseling', '0006_studyplan_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.course', verbose_name='درس (انتخاب از لیست)'),
        ),
    ]
