# Generated by Django 6.0.6 on 2026-08-24 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0007_report_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.CharField(max_length=20, verbose_name='تاریخ تماس')),
                ('contact_type', models.CharField(choices=[('call', 'تماس تلفنی'), ('text', 'پیامک'), ('video', 'تماس ویدیویی')], default='call', max_length=10, verbose_name='نوع تماس')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_contact_logs', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_contact_logs', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'لاگ تماس',
                'verbose_name_plural': 'لاگ تماس\u200cها',
                'ordering': ['-contact_date', '-created_at'],
            },
        ),
    ]
