# Generated by Django 6.0.6 on 2026-07-06 13:40

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('exam_type', models.CharField(choices=[('test', 'فقط تستی'), ('mixed', 'تستی و تشریحی')], default='test', max_length=10, verbose_name='نوع آزمون')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('entry_start', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('entry_end', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='exams/', verbose_name='فایل پیوست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='نمره کل')),
                ('exit_count', models.PositiveIntegerField(default=0, verbose_name='تعداد خروج')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exam.exam', verbose_name='آزمون')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_responses', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخنامه',
                'verbose_name_plural': 'پاسخنامه\u200cها',
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('test', 'تستی'), ('essay', 'تشریحی')], default='test', max_length=10, verbose_name='نوع سوال')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن سوال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='تصویر سوال')),
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='نمره سوال')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['order'],
                'unique_together': {('exam', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='شماره گزینه')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'test'}, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='پاسخ متنی')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='essay_answers/', verbose_name='فایل پاسخ')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره داده شده توسط مشاور')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_answers', to='exam.examresponse', verbose_name='پاسخنامه')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'essay'}, on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ تشریحی',
                'verbose_name_plural': 'پاسخ\u200cهای تشریحی',
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.choice', verbose_name='گزینه انتخاب شده')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'test'}, on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='سوال')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='exam.examresponse', verbose_name='پاسخنامه')),
            ],
            options={
                'verbose_name': 'پاسخ تستی',
                'verbose_name_plural': 'پاسخ\u200cهای تستی',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
