# Generated by Django 6.0.6 on 2026-07-29 14:40

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='entry_end',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='entry_start',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و ساعت شروع'),
        ),
    ]
