# Generated by Django 6.0.6 on 2026-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_entry_end_alter_exam_entry_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='score_type',
            field=models.CharField(choices=[('percentage', 'درصد'), ('score', 'نمره')], default='percentage', max_length=10, verbose_name='نوع نمره\u200cدهی'),
        ),
    ]
