# Generated by Django 6.0.6 on 2026-08-05 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_unique_together_and_more'),
        ('exam', '0003_exam_score_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بخش')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', verbose_name='درس مرتبط')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exam.exam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'بخش آزمون',
                'verbose_name_plural': 'بخش\u200cهای آزمون',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exam.examsection', verbose_name='بخش'),
        ),
    ]
