# Generated by Django 6.0.6 on 2026-08-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examsection_question_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='advice_text',
            field=models.TextField(blank=True, null=True, verbose_name='نصیحت مشاور'),
        ),
        migrations.AddField(
            model_name='exam',
            name='motivation_text',
            field=models.TextField(blank=True, null=True, verbose_name='جمله انگیزشی قبل از آزمون'),
        ),
    ]
