# Generated by Django 6.0.6 on 2026-07-06 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نمونه سوال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('pdf_file', models.FileField(upload_to='exam_samples/', verbose_name='فایل PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_samples', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_samples', to='core.course', verbose_name='درس')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_samples', to='core.fieldofstudy', verbose_name='رشته تحصیلی')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_samples', to='core.grade', verbose_name='پایه تحصیلی')),
            ],
            options={
                'verbose_name': 'نمونه سوال',
                'verbose_name_plural': 'نمونه سوالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جزوه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('pdf_file', models.FileField(upload_to='notes/', verbose_name='فایل PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.course', verbose_name='درس')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.fieldofstudy', verbose_name='رشته تحصیلی')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.grade', verbose_name='پایه تحصیلی')),
            ],
            options={
                'verbose_name': 'جزوه',
                'verbose_name_plural': 'جزوه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پادکست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('audio_file', models.FileField(upload_to='podcasts/', verbose_name='فایل صوتی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='فایل ویدیو')),
                ('aparat_link', models.URLField(blank=True, null=True, verbose_name='لینک آپارات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['-created_at'],
            },
        ),
    ]
