# Generated by Django 6.0.6 on 2026-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_unique_together_and_more'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsample',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='note',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='examsample',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, related_name='exam_samples', to='core.fieldofstudy', verbose_name='رشته\u200cهای تحصیلی'),
        ),
        migrations.AddField(
            model_name='note',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, related_name='notes', to='core.fieldofstudy', verbose_name='رشته\u200cهای تحصیلی'),
        ),
    ]
