# Generated by Django 6.0.6 on 2026-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_examsample_field_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsample',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='education/samples/covers/', verbose_name='تصویر نمونه سوال'),
        ),
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='education/notes/covers/', verbose_name='تصویر جلد جزوه'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='education/podcasts/covers/', verbose_name='تصویر جلد پادکست'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='education/videos/thumbnails/', verbose_name='تصویر پیش\u200cنمایش ویدیو'),
        ),
    ]
