# Generated by Django 6.0.6 on 2026-07-06 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('urgency', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('emergency', 'اورژانسی')], default='medium', max_length=10, verbose_name='میزان فوریت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('reviewing', 'در حال بررسی'), ('contacted', 'تماس گرفته شده'), ('resolved', 'حل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('psychologist_note', models.TextField(blank=True, null=True, verbose_name='یادداشت روانشناس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('psychologist', models.ForeignKey(blank=True, limit_choices_to={'role': 'psychologist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='روانشناس')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='psychology_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'درخواست روانشناسی',
                'verbose_name_plural': 'درخواست\u200cهای روانشناسی',
                'ordering': ['-created_at'],
            },
        ),
    ]
