# Generated by Django 6.0.6 on 2026-07-06 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', 'عمومی'), ('course', 'دوره آموزشی'), ('counselor', 'مشاور')], default='general', max_length=20, verbose_name='نوع کامنت')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه مرتبط')),
                ('content', models.TextField(verbose_name='متن کامنت')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز (۱ تا ۵)')),
                ('is_active', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
