# Generated by Django 6.0.6 on 2026-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='course',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.fieldofstudy', verbose_name='رشته\u200cهای مربوطه'),
        ),
    ]
