# Generated by Django 6.0.6 on 2026-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='رنگ اختصاصی (HEX)'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='default', max_length=50, verbose_name='نام فایل آیکون (بدون پسوند)'),
        ),
    ]
