# Generated by Django 6.0.6 on 2026-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_color_course_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='تصویر درس'),
        ),
    ]
