# Generated by Django 6.0.6 on 2026-08-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='color',
        ),
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
    ]
